### ISSUE TITLE
Bundled scripts do not work with --compatibility-mode=base flag

### ISSUE THREAD

**Issue by denious** [grafana/k6-template-es6#4]
Hi, I have cloned the repo, followed the build and run steps as can be seen in the screenshot below. Everything runs fine without the compatibility flag, but with the flag I get the following error:
`ERRO[0000] file:///D:/repos/template-es6/build/app.bundle.js: Line 1:16652 Unexpected reserved word (and 1451 more errors)`

I have tried [following the docs](https://k6.io/docs/using-k6/modules/#bundling-node-modules) to re-create a webpack project from scratch and got the same error when running compatibility.

Any ideas?

![image](https://user-images.githubusercontent.com/7120854/116484424-a723f880-a84e-11eb-87ba-576e9b746993.png)

**Comment by simonaronsson** [comment]
Fixed in #5

**Comment by denious** [comment]
@simskij Can you please explain the fix? You said something about cheerio, but on my side I was using faker and getting the same issue. I looked over the commit and the only thing that stood out is the `engine` change?

**Comment by simonaronsson** [comment]
> @simskij Can you please explain the fix? You said something about cheerio, but on my side I was using faker and getting the same issue. I looked over the commit and the only thing that stood out is the `engine` change? 

The big change was in the versions specified in the lock file. There was a mismatch in what packages were used.

I'll have a look at faker. From what I remember there was an issue that required you to import a specific locale.

Did you follow my article on https://dev.to/k6/performance-testing-with-generated-data-using-k6-and-faker-2e ?

**Comment by denious** [comment]
Yep, your article is how I got here :) Sounds like the changes you've made are unrelated. Let me double check everything and if I'll report back.

**Comment by simonaronsson** [comment]
Great, I'll reopen the issue meanwhile.

**Comment by denious** [comment]
Here is my fork based on your latest commits with faker added in the most minimal way possible and referencing the locale like in your article:
https://github.com/denious/template-es6

Getting the same error with base compatibility:
`ERRO[0000] file:///D:/repos/template-es6/build/app.bundle.js: Line 1:28236 Unexpected reserved word (and 1 more errors) `

**Comment by simonaronsson** [comment]
This should be fixed now. Would you mind confirming and reopening the issue if the problem persists?

**Comment by denious** [comment]
@simskij Partial success! See last updates to my fork; everything works fine until I add this line to the script dependencies:
`import { randomItem } from "https://jslib.k6.io/k6-utils/1.0.0/index.js";`

As a side note, running scripts bundled with webpack 5 is still broken. I'm not a webpack expert, so maybe it's expected, just letting you know.

**Comment by simonaronsson** [comment]
Just tried that out and it rather seems to be an issue within k6 itself, or rather compatibility mode `base` not being compatible with k6-utils due to the use of the `export` keyword. 

How we currently treat remote modules is that we mark them as external and skip them in the transpilation process, due to webpack lack of support for loading modules via HTTP. If you download the k6-utils file and reference it locally, it gets transpiled, bundled and remains runnable with `base` without issues.

You might be able to tweak your project using for instance https://github.com/roneyrao/remote-webpack-plugin to actually download and transpile the remote modules as well. However, I've not tried this plugin myself so can't really vouch for it.

Webpack 5 not working is expected, as there are breaking changes between the versions. Might upgrade the project at some point, but for now, we'll stay at 4.x. Using `npm run webpack` to bundle should ensure you avoid any version conflicts.

**Comment by denious** [comment]
@simskij Thank you for the support and the detailed answers. Could you guide me on how to reference the utils locally? I downloaded the files but regardless of how I import them, K6 complains that it cannot find the module.

The goal of the project I'm setting up is hosting all the scripts in a single project to make it easier for developers to use. The utils is the last missing piece!

**Comment by simonaronsson** [comment]
Sure! Download it and place it next to the `main.js` file, and then import it from the unpacked test using for instance
`import { randomItem } from "./k6-utils.js";`. Run webpack to have it packed into `app.bundle.js`, then run and profit 👍🏽

**Comment by denious** [comment]
Works like a charm! Thanks again!
